Rails.application.routes.draw do
  resources :passwords, param: :token
  get "users/new"
  get "users/create"
  # Existing authentication routes (generated by rails generate authentication)
  resource :session
  
  # Add these lines for user registration:
  resources :users, only: [:new, :create]
  
  # Your other routes
  resources :ingredients
  
  root "ingredients#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end
